hateoas
melmaksan/springboot_rest_app pull request #3
Opened 2023-06-12 20:55 UTC by melmaksan

add links for all controller

2023-06-17 13:09 UTC, skupt requested changes
Please make requested changes before merge. Here 7 comments at all.

2023-06-17 13:09 UTC, skupt commented on src/main/java/com/epam/esm/rest_api/dto/TagDTO.java
Add id field to all DTOs, because they are useless without id from the perspective to have an ability to make some action with entity if we do not have information how to request it without id.

2023-06-17 13:09 UTC, skupt commented on src/main/java/com/epam/esm/rest_api/dto/OrderDTO.java
Add id field to all DTOs, because they are useless without id from the perspective to have an ability to make some action with entity if we do not have information how to request it without id.

2023-06-17 13:09 UTC, skupt commented on src/main/java/com/epam/esm/rest_api/dto/LinkAssembler.java
Create custom exception class and use it here instead of re-throwing the RuntimeExeption class.

2023-06-17 13:09 UTC, skupt commented on src/main/java/com/epam/esm/rest_api/dto/LinkAssembler.java
All DTOs must have link to getting collection of its with pagination parameters. 
These params must have at least 'last' param for going (or knowing it's number taking into consideration provided page size) to last page except those that already are presented.
Consider adding 'next', 'previous' params too.

2023-06-17 13:09 UTC, skupt commented on src/main/java/com/epam/esm/rest_api/dto/LinkAssembler.java
All relations should not have whitespaces in itself

2023-06-17 13:09 UTC, skupt commented on src/main/java/com/epam/esm/rest_api/dto/OrderDTO.java
Add Lombok dependency in project and refactor all DTOs using it to get experience of using Lombok.

2023-06-17 13:09 UTC, skupt commented on src/main/java/com/epam/esm/certificate_service/service/impl/UserServiceImpl.java
Make all methods of all services transactional and optimize them with respective customization of annotation (propagation, isolation, readOnly, timeout, and rollbackFor and noRollBackFor if necessary, see [link](https://docs.spring.io/spring-framework/docs/4.2.x/spring-framework-reference/html/transaction.html#transaction-declarative-annotations).

2023-06-20 21:58 UTC, melmaksan commented on src/main/java/com/epam/esm/rest_api/dto/TagDTO.java
Added id fields.

2023-06-20 21:59 UTC, melmaksan commented on src/main/java/com/epam/esm/rest_api/dto/LinkAssembler.java
Create exception  and improve links

2023-06-20 22:00 UTC, melmaksan commented on src/main/java/com/epam/esm/rest_api/dto/LinkAssembler.java
Whitespaces was removed

2023-06-20 22:01 UTC, melmaksan commented on src/main/java/com/epam/esm/rest_api/dto/OrderDTO.java
Lombok was added

2023-06-20 22:09 UTC, melmaksan commented on src/main/java/com/epam/esm/certificate_service/service/impl/UserServiceImpl.java
Transactions was moved from DAO layer to service layer; also was set customization to transactional annotation

2023-06-21 17:04 UTC, skupt requested changes

2023-06-21 17:04 UTC, skupt commented on src/main/java/com/epam/esm/certificate_service/service/impl/GiftCertificateServiceImpl.java
> +            rollbackFor = EmptyRequestBodyException.class)
Remove this attribute due to reason described in previous comment

2023-06-21 17:04 UTC, skupt commented on src/main/java/com/epam/esm/certificate_service/service/impl/GiftCertificateServiceImpl.java
> +    @Transactional(isolation = Isolation.SERIALIZABLE, rollbackFor = NoSuchDataException.class)
Consider remove this attribute so as rollback will be done only(!) for your custom exception, but in DAO layer may be thrown another successor of RuntimeException (e.g. "HibernateException extends PersistenceException" and your tyransaction will not be rolled back.
Besides this ensure that you know differences between propagations REQUIRES and REQUIRES_NEW.

2023-06-21 17:04 UTC, skupt commented on src/main/java/com/epam/esm/certificate_service/service/impl/TagServiceImpl.java
> +    @Transactional(isolation=Isolation.SERIALIZABLE, rollbackFor = NoSuchDataException.class)
Consider remove this attribute so as rollback will be done only(!) for your custom exception, but in DAO layer may be thrown another successor of RuntimeException (e.g. "HibernateException extends PersistenceException" and your tyransaction will not be rolled back.

2023-06-21 17:04 UTC, skupt commented on src/main/java/com/epam/esm/certificate_service/service/impl/UserServiceImpl.java
Ok, Now you are aware how to set up transaction, but really necessary attribute in all transaction, that do not modify data is "readOnly = true" and everything else may be left as is (without adding additional other attributes to Transactional annotation), so find out for yourself what default values will be if you don't use additional attributes).

2023-06-21 17:04 UTC, skupt commented on src/main/java/com/epam/esm/rest_api/dto/Mapper.java
> +import static com.epam.esm.rest_api.dto.LinkAssembler.*;
Decouple mapper from LinkAssembler. You can add LinkAssempler to respective Controllers and add links to previously mapped DTOs inside them.

2023-06-21 17:04 UTC, skupt commented on src/main/java/com/epam/esm/rest_api/dto/LinkAssembler.java
> +                    getLastPage(rows, size), size).withRel(SHOW_ALL + "_certificates"));
Where are relations "last", "self"?
Correct this for all DTO's

2023-06-21 17:04 UTC, skupt commented on src/main/java/com/epam/esm/rest_api/dto/LinkAssembler.java
..."These params must have at least 'last' param for going (or knowing it's number taking into consideration provided page size) to last page except those that already are presented".
And "self" should be present too.

2023-06-22 10:58 UTC, melmaksan commented on src/main/java/com/epam/esm/rest_api/dto/LinkAssembler.java
> +                    getLastPage(rows, size), size).withRel(SHOW_ALL + "_certificates"));
Added relations "first_page" and "last_page".

2023-06-22 10:59 UTC, melmaksan commented on src/main/java/com/epam/esm/rest_api/dto/Mapper.java
> +import static com.epam.esm.rest_api.dto.LinkAssembler.*;
I think decouple is not necessary in this particular project.

2023-06-22 10:59 UTC, melmaksan commented on src/main/java/com/epam/esm/certificate_service/service/impl/TagServiceImpl.java
> +    @Transactional(isolation=Isolation.SERIALIZABLE, rollbackFor = NoSuchDataException.class)
rollbackFor attribute was removed.

2023-06-22 10:59 UTC, melmaksan commented on src/main/java/com/epam/esm/certificate_service/service/impl/GiftCertificateServiceImpl.java
> +    @Transactional(isolation = Isolation.SERIALIZABLE, rollbackFor = NoSuchDataException.class)
rollbackFor attribute was removed.

2023-06-22 10:59 UTC, melmaksan commented on src/main/java/com/epam/esm/certificate_service/service/impl/GiftCertificateServiceImpl.java
> +            rollbackFor = EmptyRequestBodyException.class)
Attributes were removed.

2023-06-22 10:59 UTC, melmaksan commented on src/main/java/com/epam/esm/certificate_service/service/impl/UserServiceImpl.java
All transactions have been corrected.

2023-06-22 10:59 UTC, melmaksan commented on src/main/java/com/epam/esm/rest_api/dto/LinkAssembler.java
Added relations "first_page" and "last_page".

2023-06-22 14:02 UTC, skupt approved these changes

2023-06-22 14:40 UTC, merged